### ISSUE TITLE
About global map generation

### ISSUE THREAD

**Issue by The-Kakarot** [Pamphlett/Outram#1]
Thank you for open-sourcing your interesting and nice work. Is the function for generating `cluster_map.pcd` and `covariances.bin` missing?

**Comment by Pamphlett** [comment]
Hi,

Thanks for your interest in our work.
Yes, we did not include these functions in our current implementation for the clarity of the whole code base.

But it would be very simple to implement oneself. Just by clustering points with the same semantic class in the global point cloud map through Euclidean clustering (we leverage the implementation in PCL FYI).

Or else we'll release our implementation in the near future. But I cannot guarantee an accurate timeline as we have a lot of work on hand.

Hope it helps.

**Comment by The-Kakarot** [comment]
Many thanks.
