### ISSUE TITLE
Preprocessing of the MulRan Dataset

### ISSUE THREAD

**Issue by bear-rabbit** [Pamphlett/Outram#5]
Hello! I apologize for bothering you again! We've encountered an issue in our recent research project on global registration based on the MulRan map. We suspect the problem lies in directly using the raw bin data without applying any distortion corrections or similar preprocessing. I would like to know if you performed any preprocessing on the MulRan dataset during your research? Apart from semantic labeling, that was our previous question (haha). I look forward to your response!

**Comment by Pamphlett** [comment]
Hello, no we did not.

**Comment by bear-rabbit** [comment]
Thank ！

**Comment by Pamphlett** [comment]
Welcome, and it would be wonderful if you give a star to our repo :)
