### ISSUE TITLE
对于mulran坐标的处理

### ISSUE THREAD

**Issue by Hfx-J** [Pamphlett/Outram#7]
我想知道您在处理mulran真值的时候对原始的xyz坐标分别减去了多少？我发现他对于结果的影响很大

**Comment by Pamphlett** [comment]
Question: I would like to know how much you subtracted from the original xyz coordinates when dealing with the MulRan ground truth?

Please refer to the code block below:
```
float_array[:, 3] -= 355630
float_array[:, 7] -= 4026791
```

**Comment by Hfx-J** [comment]
> Question: I would like to know how much you subtracted from the original xyz coordinates when dealing with the MulRan ground truth?
> 
> Please refer to the code block below:
> 
> ```
> float_array[:, 3] -= 355630
> float_array[:, 7] -= 4026791
> ```

Have you applied the same parameters when processing the ground truth for both the DCC and Kaist sequences?

**Comment by Pamphlett** [comment]
yes.

**Comment by Hfx-J** [comment]
> yes.

Hello, I encountered an issue while testing Outram. When running the DCC sequence, the program froze due to a memory overflow. However, there were no issues when running the Kaist sequence. (My device is an i7 10th gen with 32GB RAM.)

**Comment by Hfx-J** [comment]
> > yes.
> 
> Hello, I encountered an issue while testing Outram. When running the DCC sequence, the program froze due to a memory overflow. However, there were no issues when running the Kaist sequence. (My device is an i7 10th gen with 32GB RAM.)

Are there any parts of your program that require a significant amount of memory? (Aside from the visualization part, as we have already turned it off.)

**Comment by Pamphlett** [comment]
Hello,

The reason for the out-of-memory error could be you have too many semantic clusters in your current frame (please verify that from the output of the program). We tried SPVNAS on MulRan and the segmentation result is not ideal. In that case, too many clusters will result in an unmanageable maximum clique problem to solve.

A workaround is to play with the clustering parameters [here](https://github.com/Pamphlett/Outram/blob/54a3419f0090f35c207e135b6929be76e368d7dd/config/global_localization.yaml#L5). You can try to increase the number of points needed to form one semantic cluster and thus reduce the number fo it.

A better solution should be to fine-tune the current SPVCNN model to have a better segmentation result.

**Comment by Pamphlett** [comment]
Close for now, feel free to open again.
